### PR TITLE
added tests for set hide cookie

### PR DESCRIPTION
**Pull request by WMDE-Fisch**
see https://github.com/wmde/fundraising/issues/955

### CODE REVIEW

**Comment by wmde-manicki** [comment]
I forgot I wanted to ask a question. I'm not sure if this is the place to ask but I couldn't come up with better:
Tests here were good but they're only for sensitive banner and the blue/yellow banner. Given how the current code is done, those tests passing means that "normal top banners" that were are using the most are all covered. But wouldn't we also want to have a test literally for top banner?

**Comment by WMDE-Fisch** [comment]
hmmm you mean the full-top? or half-full-top? or whats it called again?

**Comment by wmde-manicki** [comment]
I mean thing like this one: https://de.wikipedia.org/wiki/78._Infanterie-Division_%28Wehrmacht%29?banner=B15WMDE_32_151214_ctrl

**Comment by wmde-manicki** [comment]
The top top

**Comment by WMDE-Fisch** [comment]
Ah yeah no, the "normal" banner is the top top. There is a refactoring PR where I also included the cookie test. The banner tests are a mess atm. The refactoring issue tries to clear some stuff.

**Comment by wmde-manicki** [comment]
That makes perfect sense then, thanks.

**Pull request merged**
